namespace Yd.Audio
{
    public enum AudioId
    {
        StoneFootstep,
        Collect,
        JumpUp,
        Land,
        Punch,
        Kick,
        PunchImpactFlesh,
        BoarAttack,
        BoarRoar,
        ConcreteFootstep,
        Desert,
        Wind,
        Forest,
        GrassFootstep,
        SandFootstep,
        StoneImpact,
        HeroDie,
        ButtonHover,
        ButtonClick,
        ChestUnlock,
        BookPage,
        HeroBreath,
        LavaAttack,
        LavaDie,
        LavaBreath,
        LavaGrowls,
        SwordSwing,
        FireballExplosion,
        FireballWhoosh
    }
}